name: hackbulgaria-algorithms
markdown: redcarpet
highlighter: pygments

collections:
  news:
    output: true
  lectures:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      reveal:
        controls: true
        progress: true
        slideNumber: false
        history: true
        keyboard: true
        overview: true
        center: true
        touch: true
        loop: false
        rtl: false
        fragments: true
        embedded: false
        autoSlide: 0
        autoSlideStoppable: true
        mouseWheel: false
        hideAddressBar: true
        previewLinks: false
        transition: slide
        transitionSpeed: default
        backgroundTransition: default
        viewDistance: 3
        parallaxBackgroundImage:
        parallaxBackgroundSize:
        theme: lecture
